Ma 8080 upload support
Staffbase/trigger.io-tabs pull request #5
Opened 2018-10-17 09:11 UTC by hassaanz

The PR adds support for file input type in the Web View for android.

To Test:
- Open Frontend Repo
- Change "tabs" in client/config/config.json to "sb_tabs"
- Change Version of sb_tabs to 2.32.6
- Build a native android app: grunt run_android:staffbasetest --ac=test
- Install app on device.
- Open a link which contains file upload with "External Link" plugin in the app
- Check if file chooser works fine
- Verify that mime types are also respected for input field

2018-10-18 09:37 UTC, Drako approved these changes

2018-10-18 11:11 UTC, karanadvani commented
@hassaanz 
**Observations**
- Works fine with accept="image/*"
- But if we put specific formats like accept=".jpg, .jpeg, .png" it also accepts .gif,.mp4
- Does not work for other formats like .pdf, .doc, .docx, .xls etc.

2018-10-18 11:13 UTC, karanadvani commented
Used this link to test - https://ma-8080-fxqxtkmilq.now.sh

2018-10-22 13:17 UTC, Drako requested changes

2018-10-22 13:17 UTC, Drako commented on inspector/an-inspector/ForgeModule/src/io/trigger/forge/android/modules/tabs/ModalView.java
> +        if (mimeTypes.contains(",")) {
u wot m8?

2018-10-22 13:17 UTC, Drako commented on inspector/an-inspector/ForgeModule/src/io/trigger/forge/android/modules/tabs/ModalView.java
> +        String[] mimeTypesArray = null;
this could be
`final String[] mimeTypesArray = mimeTypes.split(",");`

2018-10-24 13:34 UTC, merged

2018-10-25 09:14 UTC, karanadvani commented
Works fine with Google Drive and Default Android File Chooser. 
But fails when we access the files through File Manager as I feel we can't restrict the file types on it.